# Default values for colorex-ifs-rsync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
colorex-ifs-rsync:
  image:
    # Your docker image.
    repository: docker.artifactory.sherwin.com/sherwin-williams-co/colorex-ifs-rsync
    pullPolicy: IfNotPresent
  #Will override defaultTag if uncommented.  Default tag is the same as the version in Chart.yaml.
    #tag: "v0.1.160"
  
  deployment:
    name: ifs-reader
  
  store: 
    enabled: false
  
  
  pv:
    name: ifs-pv
  
  local:
    enabled: false
  
  createStorage: false
  
  test: false
  
  #Default port will get overridden by environment
  service:
    ifsReader:
      nodePort: 0
    ifsWriter:
      nodePort: 0
  
  #Default Vault Role
  vault:
    role: defaultRole
  
  ingress:
    hostname: np-rancher.sherwin.com
  
  pvc:
    name: ifs-pvc
    storageClassName: longhorn
    storageSize: 1Gi
  


