apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: sandbox
spec:
  vault:
    path: cagw/sign/sw_issuing_ca
    server: https://vault.sherwin.com
    auth:
      kubernetes:
        role: k8s-pr-tag-depot1-certmanager
        mountPath: /v1/auth/kubernetes-pr-tag-depot1
        serviceAccountRef:
          name: vault-issuer
