apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cluster-lab'
  annotations:
    argocd.argoproj.io/sync-wave: '25'
  labels:
    app.kubernetes.io/name: 'cluster-lab'
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: 'https://github.com/fxs72r/codefresh-isc.git'
    path: 'clusters/overlays/lab/helm'
    targetRevision: 'HEAD'
    helm:
      releaseName: 'shw-cluster'
      skipCrds: false
      parameters:
      - name: longhorn.ingress.host
        value: longhorn.lb9001-ingress.stores.sherwin.com
      valueFiles:
      - values.yaml
#    - repoURL: 'https://github.com/sherwin-williams-co/na-pos-deploy.git'
#      targetRevision: 'HEAD'
#      path: 'clusters/overlays/lab/sites/{{ name }}/resources-cluster'
#      plugin:
#        name: argocd-vault-plugin-kustomize
  destination:
#    namespace: 'shw-cluster'
#    server: '{{ shw.url }}'
    namespace: codefresh
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.conversion.webhook.clientConfig.caBundle
    - .spec.conversion.webhook.clientConfig.service.name
    - .spec.conversion.webhook.clientConfig.service.namespace
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
    - '.webhooks[]?.client'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - Validate=true
