apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-source-lb9961
  labels:
    codefresh.io/entity: git-source
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fxs72r/codefresh-isc.git
    path: git-source-lb9961
    targetRevision: master
    directory:
      include: ''
      exclude: ''
      recurse: true
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
